on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Merge by labeled
        uses: KrutiAmrutiya/CI-CD@main
        with:
          label_name: 'merged in main'
          target_branch: 'develop'
